/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DailyQuoteRouteImport } from './routes/daily-quote'
import { Route as EventsRouteImport } from './routes/events'
import { Route as FacultyRouteImport } from './routes/faculty'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as PrincipalMessageRouteImport } from './routes/principal-message'
import { Route as ResultsRouteImport } from './routes/results'
import { Route as NewsIndexRouteImport } from './routes/news.index'
import { Route as NewsSlugRouteImport } from './routes/news.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DailyQuoteRoute = DailyQuoteRouteImport.update({
  id: '/daily-quote',
  path: '/daily-quote',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const FacultyRoute = FacultyRouteImport.update({
  id: '/faculty',
  path: '/faculty',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const PrincipalMessageRoute = PrincipalMessageRouteImport.update({
  id: '/principal-message',
  path: '/principal-message',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultsRoute = ResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsIndexRoute = NewsIndexRouteImport.update({
  id: '/news/',
  path: '/news/',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsSlugRoute = NewsSlugRouteImport.update({
  id: '/news/$slug',
  path: '/news/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/daily-quote': typeof DailyQuoteRoute
  '/events': typeof EventsRoute
  '/faculty': typeof FacultyRoute
  '/gallery': typeof GalleryRoute
  '/principal-message': typeof PrincipalMessageRoute
  '/results': typeof ResultsRoute
  '/news/$slug': typeof NewsSlugRoute
  '/news/': typeof NewsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/daily-quote': typeof DailyQuoteRoute
  '/events': typeof EventsRoute
  '/faculty': typeof FacultyRoute
  '/gallery': typeof GalleryRoute
  '/principal-message': typeof PrincipalMessageRoute
  '/results': typeof ResultsRoute
  '/news/$slug': typeof NewsSlugRoute
  '/news': typeof NewsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/daily-quote': typeof DailyQuoteRoute
  '/events': typeof EventsRoute
  '/faculty': typeof FacultyRoute
  '/gallery': typeof GalleryRoute
  '/principal-message': typeof PrincipalMessageRoute
  '/results': typeof ResultsRoute
  '/news/$slug': typeof NewsSlugRoute
  '/news/': typeof NewsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/daily-quote'
    | '/events'
    | '/faculty'
    | '/gallery'
    | '/principal-message'
    | '/results'
    | '/news/$slug'
    | '/news/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/daily-quote'
    | '/events'
    | '/faculty'
    | '/gallery'
    | '/principal-message'
    | '/results'
    | '/news/$slug'
    | '/news'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/daily-quote'
    | '/events'
    | '/faculty'
    | '/gallery'
    | '/principal-message'
    | '/results'
    | '/news/$slug'
    | '/news/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  DailyQuoteRoute: typeof DailyQuoteRoute
  EventsRoute: typeof EventsRoute
  FacultyRoute: typeof FacultyRoute
  GalleryRoute: typeof GalleryRoute
  PrincipalMessageRoute: typeof PrincipalMessageRoute
  ResultsRoute: typeof ResultsRoute
  NewsSlugRoute: typeof NewsSlugRoute
  NewsIndexRoute: typeof NewsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/daily-quote': {
      id: '/daily-quote'
      path: '/daily-quote'
      fullPath: '/daily-quote'
      preLoaderRoute: typeof DailyQuoteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faculty': {
      id: '/faculty'
      path: '/faculty'
      fullPath: '/faculty'
      preLoaderRoute: typeof FacultyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/principal-message': {
      id: '/principal-message'
      path: '/principal-message'
      fullPath: '/principal-message'
      preLoaderRoute: typeof PrincipalMessageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/results': {
      id: '/results'
      path: '/results'
      fullPath: '/results'
      preLoaderRoute: typeof ResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news/': {
      id: '/news/'
      path: '/news'
      fullPath: '/news/'
      preLoaderRoute: typeof NewsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news/$slug': {
      id: '/news/$slug'
      path: '/news/$slug'
      fullPath: '/news/$slug'
      preLoaderRoute: typeof NewsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  DailyQuoteRoute: DailyQuoteRoute,
  EventsRoute: EventsRoute,
  FacultyRoute: FacultyRoute,
  GalleryRoute: GalleryRoute,
  PrincipalMessageRoute: PrincipalMessageRoute,
  ResultsRoute: ResultsRoute,
  NewsSlugRoute: NewsSlugRoute,
  NewsIndexRoute: NewsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
